### ISSUE TITLE
Random error in InProcessChroncileTest under load.

### ISSUE THREAD

**Issue by peter-lawrey** [peter-lawrey/Java-Chronicle#23]
testOverTCP(com.higherfrequencytrading.chronicle.impl.InProcessChronicleTest)  Time elapsed: 0.07 sec  <<< ERROR!
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:478)
	at java.nio.DirectByteBuffer.getLong(DirectByteBuffer.java:731)
	at com.higherfrequencytrading.chronicle.tcp.InProcessChronicleSink.readNextExcerpt(InProcessChronicleSink.java:171)
	at com.higherfrequencytrading.chronicle.tcp.InProcessChronicleSink.readNext(InProcessChronicleSink.java:117)
	at com.higherfrequencytrading.chronicle.tcp.InProcessChronicleSink$SinkExcerpt.nextIndex(InProcessChronicleSink.java:96)
	at com.higherfrequencytrading.chronicle.impl.InProcessChronicleTest.testOverTCP(InProcessChronicleTest.java:78)

Fine when run by itself.

**Comment by peter-lawrey** [comment]
The current version is Chronicle Queue v4.
